Final-Project-Team6/BE_Project

.github/workflows/main.yml
aptner/appspec.yml
aptner/deploy.sh

- main.yml (빌드 및 jar 버킷 업로드)
- appspec.yml (배포 프로세스 정의, 파일 복사, 권한 설정, deploy.sh 실행)
- deploy.sh ( 실행 중인 서버 중단 및 새로운 서버 실행) 
- 관련 이슈 #4  참고

👷CICD: CI/CD 빌드 시스템

---

aptner/build.gradle
aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
aptner/src/main/resources/application.properties

✨ENH : springdoc-swagger

---

.github/ISSUE_TEMPLATE/issue-template.md
.github/pull_request_template.md
.github/workflows/main.yml
aptner/appspec.yml
aptner/build.gradle
aptner/deploy.sh
aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
aptner/src/main/resources/application.properties

Deploy 4/30

---

aptner/build.gradle

dev 에 누락된 Build.gradle 을 다시 추가한다.

dev 에 누락된 Build.gradle 을 다시 추가한다.

---

.github/workflows/main.yml

- #23   
- 배포 시 빠진 부분 긴급 수정.
- main.yml 의 --exclude-task test 테스트 제외 코드 삽입

🚑FIX : main.yml 수정

---

aptner/src/main/java/com/fastcampus/aptner/global/handler/common/BaseTimeEntity.java
aptner/src/main/java/com/fastcampus/aptner/jwt/domain/TokenStorage.java
aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/domain/CommunicationComment.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/repository/CommunicationVoteRepository.java
aptner/src/main/java/com/fastcampus/aptner/post/information/repository/InformationCategoryRepository.java
aptner/src/main/java/com/fastcampus/aptner/post/information/repository/InformationRepository.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

🎉INIT: 프로젝트 시작

---

aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
aptner/src/main/java/com/fastcampus/aptner/member/domain/Subscription.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/SignUpMemberRequest.java

-  MySQL 속성에 따라 엔티티에서 크기 지정하기
-  DTO 클래스 안에 정규표현식으로 데이터 형식 검증하기
자바와 데이터베이스를 고려하면서 요구사항에 따라 필드 크기를 모두 변경했고, DTO 에서 정규 표현식으로 모두 작성했다.
`@Column`을 `@Size` 와 함께 사용하여 Bean 유효성 검사와 함께 데이터베이스 열 속성을 지정할 수 있다.
**`Difference Between @Size, @Length, and @column(length=value)`** 밸덩
- https://www.baeldung.com/jpa-size-length-column-differences
**`@Size, @Length, @Column`** 정리한 위키
- https://github.com/Final-Project-Team6/BE_Project/wiki/@Column,-@Size,-@NotNull-%EC%A4%91%EC%97%90%EC%84%9C-%EC%84%A0%ED%83%9D%EC%9D%80%3F
@cutegyuseok @NaSJ93 
This closes #30

회원 엔티티 및 DTO 생성하기

---

aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/AnnouncementController.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/repository/AnnouncementRepositoryDslImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDslImpl.java

🔀MERG : Hotfix

---

aptner/src/main/java/com/fastcampus/aptner/AptnerApplication.java
aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/SignInMemberController.java

✨ENH : CORS

---

aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java

✨ENH : Swagger Server Url Setting

---

aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationCategoryController.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationController.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/domain/Communication.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/domain/CommunicationCategory.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/dto/CommunicationDTO.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCategoryService.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCategoryServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationService.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/controller/InformationCategoryController.java
aptner/src/main/java/com/fastcampus/aptner/post/information/controller/InformationController.java
aptner/src/main/java/com/fastcampus/aptner/post/information/domain/Information.java
aptner/src/main/java/com/fastcampus/aptner/post/information/domain/InformationCategory.java
aptner/src/main/java/com/fastcampus/aptner/post/information/dto/InformationDTO.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationCategoryService.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationCategoryServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationService.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationServiceImpl.java

- Change 1
- Description
- Change 2
- Description

Communication, Information 첫 pr

---

aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationCategoryController.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintController.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepositoryDslImpl.java

기존 게시글 목록 조회 API 에 Boolean  형태의 내 민원 목록 조회 기능 추가
- 소통 게시판 URL 수정

✨ENH : 내 민원 목록 조회

---

aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
aptner/src/main/java/com/fastcampus/aptner/apartment/controller/UpdateApartmentController.java
aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/LogoutMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java

회원은 모두 API 명을 member 으로 시작하도록 변경하고 스웨거도 따라서 변경된다.

회원 API 수정 및 아파트, 회원 스웨거 변경하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberRequest.java

아파트 이름 -> 아파트 ID 으로 요청 받을 수 있도록 변경하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 로그인 DTO 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberRequest.java

♻️REF : 회원 로그인 스웨거 수정하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 회원 로그인 스웨거 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java

Deploy 5/24

---

aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
aptner/src/main/java/com/fastcampus/aptner/apartment/domain/Apartment.java
aptner/src/main/java/com/fastcampus/aptner/apartment/dto/CreateApartmentRequest.java
aptner/src/main/java/com/fastcampus/aptner/apartment/dto/FindApartmentResponse.java
aptner/src/main/java/com/fastcampus/aptner/apartment/repository/ApartmentRepository.java
aptner/src/main/java/com/fastcampus/aptner/apartment/service/CreateApartmentServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/apartment/service/FindApartmentService.java
aptner/src/main/java/com/fastcampus/aptner/apartment/service/FindApartmentServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberRequest.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCategoryServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCommonServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementAdminServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementCategoryAdminServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/common/error/PostErrorCode.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCommonService.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCommonServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryController.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryService.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCommonServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintAdminServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintCategoryAdminServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java

Deploy 0524-2

---

aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/AnnouncementController.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/VoteController.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Vote.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteService.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java

- 공감기능 수정 API 추가
- 잘못 들어간 확인 코드 삭제

✨ENH : 공감기능 수정 API

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

더이상 사용되지 않은 import 를 제거하고, 로그인에 @Valid 추가하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 불필요한 import 및 @Valid 추가하기

---

aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/admin/CommunicationAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/admin/CommunicationCategoryAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/domain/CommunicationType.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/repository/CommunicationRepositoryDsl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/repository/CommunicationRepositoryDslImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/admin/CommunicationAdminService.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/admin/CommunicationAdminServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/admin/CommunicationCategoryAdminService.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/admin/CommunicationCategoryAdminServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/controller/admin/InformationAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/information/controller/admin/InformationCategoryAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/information/domain/InformationType.java
aptner/src/main/java/com/fastcampus/aptner/post/information/repository/InformationRepositoryDsl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/repository/InformationRepositoryDslImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationCategoryService.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationCategoryServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationService.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationServiceImpl.java

- Change 1
- Description
- Change 2
- Description

정보,소통 게시판 나머지 파일 전송

---

aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java

♻️REF : 스웨거 권한 설정하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 스웨거 권한 설정하기

---

aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java

- Change 1
- Description
- Change 2
- Description

♻️REF : 스웨거 권한 확인 및 재설정하기

---

aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationCategoryController.java

- Change 1
- Description
- Change 2
- Description

🚑FIX : 소통공간 카테고리 컨트롤러 오타 수정

---

aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementCategoryAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryAdminController.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

✨ENH : security 에 맞춰 관리자 url 수정

---

aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementCategoryAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationCategoryController.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryAdminController.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java

Deploy 05/27

---

aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java

시큐리티 URL 경로를 적절하게 설정하고 Member 에서 불필요한 필드를 제거한다.
- Change 1
- Description
- Change 2
- Description

경로에 따른 권한 설정 및 불필요한 필드 제거하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/HttpResponse.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/JoinMemberRequest.java
aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

불필요한 임포트 삭제 및 경로 설정하기
- Change 1
- Description
- Change 2
- Description

불필요한 임포트 삭제 및 경로 설정하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java

🚑FIX : 회원 스웨거 수정하기
- Change 1
- Description
- Change 2
- Description

 🚑FIX : 회원 스웨거 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

♻️REF : 시큐리티 경로 수정하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 시큐리티 경로 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateMemberProfileRequest.java
aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberService.java
aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java

✨ENH :회원 이미지 필드 추가 및 수정 추가하기
- Change 1
- Description
- Change 2
- Description

✨ENH :회원 이미지 필드 추가 및 수정 추가하기

---

aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintController.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepositoryDslImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/CommentController.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Comment.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/dto/CommentDTO.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDsl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDslImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentService.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteService.java
aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java

✨ENH : 민원글 검색 날짜 조건 추가
✨ENH : 내 댓글 목록 보기 기능

✨ENH : 내 댓글 목록 보기 기능

---

aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationController.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/admin/CommunicationAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/admin/CommunicationCategoryAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/domain/Communication.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/dto/CommunicationDTO.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/repository/CommunicationRepositoryDsl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/repository/CommunicationRepositoryDslImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCategoryServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationService.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/admin/CommunicationCategoryAdminServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/controller/InformationCategoryController.java
aptner/src/main/java/com/fastcampus/aptner/post/information/controller/InformationController.java
aptner/src/main/java/com/fastcampus/aptner/post/information/controller/admin/InformationAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/information/controller/admin/InformationCategoryAdminController.java
aptner/src/main/java/com/fastcampus/aptner/post/information/dto/InformationDTO.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationCategoryServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationService.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/admin/InformationAdminServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/information/service/admin/InformationCategoryAdminServiceImpl.java

- Change 1
- Description
- Change 2
- Description

정보,소통 공간 수정

---

aptner/src/main/java/com/fastcampus/aptner/member/service/MemberCommonServiceImpl.java

✨ENH : commonservice 회원 id 받도록 수정하기
- Change 1
- Description
- Change 2
- Description

✨ENH : commonservice 회원 id 받도록 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/post/communication/service/admin/CommunicationAdminServiceImpl.java

- Change 1
- Description
- Change 2
- Description

소통게시판 기능 수정

---

aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java

🚑FIX : 성별, 주민등록번호 앞자리 인증 없는 회원 가입 가능하도록 변경하기
- Change 1
- Description
- Change 2
- Description

🚑FIX : 성별, 주민등록번호 앞자리 인증 없는 회원 가입 가능하도록 변경하기

---

aptner/src/main/java/com/fastcampus/aptner/global/error/GlobalExceptionHandler.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java

회원 유휴성 검사에 공백, 적절한 입력 확인하고 메시지를 적절하게 응답할 수 있도록 추가하자.
- Change 1
- Description
- Change 2
- Description

회원 유효성 검사 시점 추가하기

---

aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

♻️REF : 유효성 검사 요청을 모두 허용하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 유효성 검사 요청을 모두 허용하기

---

aptner/src/main/java/com/fastcampus/aptner/AptnerApplication.java
aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
aptner/src/main/java/com/fastcampus/aptner/jwt/domain/TokenStorage.java
aptner/src/main/java/com/fastcampus/aptner/jwt/filter/JwtAuthenticationFilter.java
aptner/src/main/java/com/fastcampus/aptner/jwt/repository/RefreshTokenRepository.java
aptner/src/main/java/com/fastcampus/aptner/jwt/service/RefreshTokenService.java
aptner/src/main/java/com/fastcampus/aptner/jwt/util/JwtTokenizer.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/LogoutMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/service/LoginMemberService.java
aptner/src/main/java/com/fastcampus/aptner/member/service/loginMemberServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/redis/config/RedisConfig.java
aptner/src/main/java/com/fastcampus/aptner/redis/util/RedisUtils.java

✨ENH : 리프레시 토큰 MySQL 에서 Redis 으로 수정하기
- Change 1
- Description
- Change 2
- Description

✨ENH : 리프레시 토큰 MySQL 에서 Redis 으로 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/AptnerApplication.java
aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
aptner/src/main/java/com/fastcampus/aptner/jwt/domain/TokenStorage.java
aptner/src/main/java/com/fastcampus/aptner/jwt/filter/JwtAuthenticationFilter.java
aptner/src/main/java/com/fastcampus/aptner/jwt/repository/RefreshTokenRepository.java
aptner/src/main/java/com/fastcampus/aptner/jwt/service/RefreshTokenService.java
aptner/src/main/java/com/fastcampus/aptner/jwt/util/JwtTokenizer.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/LogoutMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/service/LoginMemberService.java
aptner/src/main/java/com/fastcampus/aptner/member/service/loginMemberServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/redis/config/RedisConfig.java
aptner/src/main/java/com/fastcampus/aptner/redis/util/RedisUtils.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

Deploy 06/02 

---

aptner/src/main/java/com/fastcampus/aptner/post/communication/dto/CommunicationDTO.java

- Change 1
- Description
- Change 2
- Description

✨ENH : 소통글 검색시 비밀여부 출력되게

---

aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java

잘못된 입력을 수정한다. nickname 으로 올바르게 수정이다.
- Change 1
- Description
- Change 2
- Description

♻️REF : 회원 응답DTO 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/apartment/repository/HomeRepository.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/response/MemberInformationResponse.java
aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberService.java
aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java

✨ENH : 회원 정보 조회 생성하기
- Change 1
- Description
- Change 2
- Description

✨ENH : 회원 정보 조회 생성하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java

♻️REF : 회원 정보 조회 수정하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 회원 정보 조회 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/MemberHomeController.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/response/MemberInformationResponse.java
aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberHomeRepository.java
aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberHomeRepositoryCustom.java
aptner/src/main/java/com/fastcampus/aptner/member/service/MemberHomeService.java
aptner/src/main/java/com/fastcampus/aptner/member/service/MemberHomeServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java

✨ENH :  회원 정보 조회 및 아파트별 자택 조회 추가하기
- Change 1
- Description
- Change 2
- Description

✨ENH :  회원 정보 조회 및 아파트별 자택 조회 추가하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/MemberHomeController.java

♻️REF : 아파트별 회원 자택 조회 스웨거 수정하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 아파트별 회원 자택 조회 스웨거 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/MemberHomeController.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/response/PostMemberResponse.java

Deploy 0606

---

aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java

♻️REF : 게시글 카테고리 응답값 통일

---

aptner/src/main/java/com/fastcampus/aptner/member/dto/response/PostMemberResponse.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java

Deploy 0606-2

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/response/LoginMemberResponse.java
aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java

✨ENH : 회원 로그인 응답 수정 및 회원 이미지 예외 검증 추가하기
- Change 1
- Description
- Change 2
- Description

✨ENH : 회원 로그인 응답 수정 및 회원 이미지 예외 검증 추가하기

---

aptner/src/main/java/com/fastcampus/aptner/apartment/controller/CreateApartmentController.java
aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
aptner/src/main/java/com/fastcampus/aptner/apartment/controller/UpdateApartmentController.java
aptner/src/main/java/com/fastcampus/aptner/apartment/domain/Apartment.java
aptner/src/main/java/com/fastcampus/aptner/apartment/dto/CreateApartmentRequest.java
aptner/src/main/java/com/fastcampus/aptner/apartment/service/CreateApartmentServiceImpl.java

✨ENH : 아파트 스웨거 정리하기
- Change 1
- Description
- Change 2
- Description

✨ENH : 아파트 스웨거 정리하기

---

aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

♻️REF : 파일 업로드, 리프레시 토큰 권한 수정하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 파일 업로드, 리프레시 토큰 권한 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/member/controller/FindMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/FindPasswordRequest.java
aptner/src/main/java/com/fastcampus/aptner/member/dto/response/FindUsernameResponse.java
aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRepository.java
aptner/src/main/java/com/fastcampus/aptner/member/service/FindMemberService.java
aptner/src/main/java/com/fastcampus/aptner/member/service/FindMemberServiceImpl.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

✨ENH :  ♻️REF :  회원 아이디, 비밀번호 찾기 엔드포인트 생성 및  설정하기
- Change 1
- Description
- Change 2
- Description

✨ENH :  ♻️REF :  회원 아이디, 비밀번호 찾기 엔드포인트 생성 및  설정하기

---

aptner/src/main/java/com/fastcampus/aptner/apartment/controller/CreateApartmentController.java
aptner/src/main/java/com/fastcampus/aptner/apartment/controller/UpdateApartmentController.java

♻️REF :  아파트 스웨거 수정하기
- Change 1
- Description
- Change 2
- Description

♻️REF :  아파트 스웨거 수정하기

---

aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java

♻️REF : 리프레시 토큰 엔드포인트 변경하기
- Change 1
- Description
- Change 2
- Description

♻️REF : 리프레시 토큰 엔드포인트 변경하기

---

aptner/src/main/java/com/fastcampus/aptner/post/announcement/dto/AnnouncementDTO.java
aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java

- Change 1
- Description
- Change 2
- Description

✨FIX : 조회시 contents 조회 안되는 문제 수정

---

aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationServiceImpl.java

- Change 1
- Description
- Change 2
- Description

✨FIX : 소통글을 로그인 한 유저만 조회 가능한 문제 수정
